# Generated by Django 4.2.11 on 2024-03-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(verbose_name='Номер номера'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.typerooms', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='size',
            field=models.IntegerField(verbose_name='Размер комнаты в м2'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='type_bed',
            field=models.CharField(max_length=100, verbose_name='Размер кровати'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='view_window',
            field=models.CharField(max_length=100, verbose_name='Вид из окна'),
        ),
        migrations.AlterField(
            model_name='typerooms',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typerooms',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип номера на английском'),
        ),
        migrations.AlterField(
            model_name='typerooms',
            name='type_rus',
            field=models.CharField(max_length=100, verbose_name='Тип номера на русском'),
        ),
    ]
