# Generated by Django 4.2.11 on 2024-03-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_price_alter_rooms_room_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typerooms',
            options={'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
    ]
