# Generated by Django 4.2.11 on 2024-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'Ожидает подтверждения'), ('cancelled', 'Отменено')], max_length=20)),
            ],
        ),
    ]
