# Generated by Django 4.2.11 on 2024-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'Ожидает подтверждения'), ('cancelled', 'Отменено')], max_length=20, verbose_name='Статус'),
        ),
    ]
