# Generated by Django 4.2.11 on 2024-04-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ('check_in_date',), 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
    ]
