# Generated by Django 4.2.11 on 2024-04-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_alter_typerooms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id гостя')),
                ('passport', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('number_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms', verbose_name='Номер номера')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='GuestServices',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('service_name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('guest_id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest', verbose_name='Id гостя')),
            ],
        ),
    ]
