# Generated by Django 4.2.11 on 2024-04-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestservices',
            options={'verbose_name': 'Услуга в номер', 'verbose_name_plural': 'Услуги в номер'},
        ),
    ]
