# Generated by Django 4.2.11 on 2024-04-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_typerooms_options'),
        ('guests', '0002_alter_guestservices_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestservices',
            name='number_room',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms', verbose_name='Номер комнаты'),
        ),
    ]
