# Generated by Django 4.2.11 on 2024-04-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guestservices_number_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestservices',
            name='number_room',
        ),
    ]
