# Generated by Django 4.2.11 on 2024-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequests',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заявки на звонок')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'ordering': ('date_added',),
            },
        ),
    ]
